baseURL = "https://bitcolabs.netlify.com"
googleAnalytics = ""
theme = "omega"
title = "BITCOLABS"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "What We Do"
pre = "#"
url = "what-we-do"
weight = "3"
[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 4
[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 5
[params]
author = "Bitco Labs"
contact_info = "Charlotte <br> North Carolina <br> "
description = "We help invest in cryptocurrencies, integrate businesses in the blockchain, and build NFTs."
logo = "images/logo.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = ""
map_center_lat = ""
map_center_lng = ""
map_marker = "images/map-marker.png"
map_position_lat = ""
map_position_lng = ""
[[params.social]]
icon = ""
link = ""
title = ""
[[params.social]]
icon = "fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/bitcolabs"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "fa-github"
link = "#"
title = "github"
[[params.social]]
icon = "fa-envelope"
link = "mailto:info@bitcolabs.com"
title = "email"
